
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim-v
  
  labels:
    app: wordpress-v
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-v
  labels:
    app: wordpress-v
spec:
  selector:
    matchLabels:
      app: wordpress-v
      tier: frontend-v
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-v
        tier: frontend-v
    spec:
      containers:
        - image: wordpress:5.4-apache
          name: wordpress-v
          env:
            - name: WORDPRESS_DB_HOST
              value: wordpress-mariadb-v
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-pass-v
                  key: password
          ports:
            - containerPort: 80
              name: wordpress-v
          volumeMounts:
            - name: wordpress-persistent-storage-v
              mountPath: /var/www/html
          resources:
            limits:
              cpu: '1'
              memory: '512Mi'
            requests:
              cpu: '500m'
              memory: '256Mi'
      volumes:
        - name: wordpress-persistent-storage-v
          persistentVolumeClaim:
            claimName: wp-pv-claim-v

---
apiVersion: v1
kind: Service
metadata:
  name: vword
spec:
  selector:
    app: wordpress-v
    tier: frontend-v  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-myservicea
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: my.example.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vword
            port:
              number: 80
  
